export const skills = [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React.Js",
    "Next.Js",
    "Redux",
    "Redux Toolkit",
    "Zustand",
    "React Query",
    "Tailwind CSS",
    "Bootstrap",
    "ShadCn",
    "Nodejs",
    "Express",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "RESTful APIs",
    "GraphQL",
    "WebSockets",
    "Git",
    "GitHub",
    "Gitlab",
    "Cypress",
    "Jest",
    "Playwright",
    "DotNet",
    "Java",
    "Python",
    "C#",
  ];
  
  export const experience = [
    {
      id: 0,
      title: "Software Developer",
      company: "Innovate Tech",
      role: "Fullstack developer",
      location: "Baluwatar, Kathmandu, Nepal",
      date: "5 July, 2024 - present",
      description: [
        "Spearheaded the end-to-end development and implementation of dynamic, high-performance web applications, contributing across database design, backend API development (Node.js), and intuitive user interfaces (React.js, TypeScript).",
        "Engineered and optimized new core UI features, establishing a library of reusable, scalable components that accelerated future development cycles.",
        "Designed and integrated robust RESTful APIs, ensuring seamless data flow, optimized data fetching strategies, and strong backend-frontend communication.",
        "Actively contributed to all phases of the software development life cycle, from conceptualization and design to deployment and performance monitoring, in an agile environment.",
      ],
      tech: [
        "HTML",
        "CSS",
        "React",
        "Node.js",
        "Express",
        "MongoDB",
        "TypeScript",
        "React Query",
        "RTK Query",
        "Next.Js",
        "TailwindCSS",
        "BootStrap",
        "Socket.io",
      ],
    },
    {
      id: 1,
      title: "Frontend Developer",
      company: "Naxa Pvt Ltd",
      role: "React frontend developer trainee",
      location: "Do Cha Marg, Maharajgunj-3, Kathmandu, Nepal",
      date: "5 Sep 2023 - 28 June 2024",
      description: [
        "Developed and meticulously maintained highly responsive and interactive UIs for cutting-edge geospatial web applications, enhancing user engagement and data visualization.",
        "Optimized complex frontend state management and data fetching strategies using React Query and Redux Toolkit, significantly improving application responsiveness and reducing load times by 10%.",
        "Proficiently managed version control using Git/GitHub, actively collaborating within an Agile team to ensure stable releases and streamline development workflows.",
      ],
      tech: [
        "HTML",
        "CSS",
        "React.js",
        "JavaScript",
        "TypeScript",
        "ShadCn",
        "TailwindCSS",
        "WEB GIS",
        "OpenLayers",
        "MaplibreGL",
        "Jest",
      ],
    },
    {
      id: 2,
      title: "Frontend Developer Intern",
      company: "Naxa Pvt Ltd",
      role: "React frontend developer intern",
      location: "Do Cha Marg, Maharajgunj-3, Kathmandu, Nepal",
      date: "5 June, 2022 - 5 Sep, 2023",
      description: [
        "Actively contributed to the development of responsive React.js UIs, implementing new features and effectively managing application state with Redux to ensure data consistency and responsiveness.",
        "Collaborated closely with senior developers on critical front-end tasks, utilizing Git/GitHub for streamlined code integration and version control, contributing to timely project milestones.",
      ],
      tech: [
        "HTML",
        "CSS",
        "React.js",
        "JavaScript",
        "TypeScript",
        "ShadCn",
        "TailwindCSS",
        "WEB GIS",
        "OpenLayers",
        "MaplibreGL",
        "Jest",
      ],
    },
  ];